spring:
  application:
    name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    rabbitmq:
      queue: zipkin
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath:schema.sql
  jpa:
    show-sql: true
  h2:
    console:
      path: /console
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 1090

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
