spring:
  application:
    name: admin-server
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: admin-server
        # MQ的配置
#        location: http://localhost:${turbine.stream.port}/
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://peer1:1000/eureka/
server:
  port: 1070

turbine:
  app-config: user-service
  cluster-name-expression: "'default'"
  # MQ的配置
#  stream:
#    port: 8088

management:
  security:
    # 禁用actuator鉴权
    enabled: false

security:
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}
