spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Chendehe1!
    # 配置druid数据源，否则MybatisConfig找不到DataSource
    type: com.alibaba.druid.pool.DruidDataSource

jedis:
  host: 192.168.111.128
  port: 6379

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

logging:
  level: info

management:
  security:
    # 禁用actuator鉴权
    enabled: false

test:
  config: aaa

---
spring:
  profiles: peer1
server:
  port: 1111
---
spring:
  profiles: peer2
server:
  port: 1112
# 访问方式 http://miniweb:miniweb@localhost:1112
#security:
#  basic:
#    enabled: true
#  user:
#    name: miniweb
#    password: miniweb
#    role:
#    - USER
#  sessions: STATELESS


