spring:
  application:
    name: order-service

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

logging:
  level: info

management:
  security:
    # 禁用actuator鉴权
    enabled: false

test:
  config: B

---
spring:
  profiles: peer1
server:
  port: 1111
---
spring:
  profiles: peer2
server:
  port: 1112
# 访问方式 http://miniweb:miniweb@localhost:1112
#security:
#  basic:
#    enabled: true
#  user:
#    name: miniweb
#    password: miniweb
#    role:
#    - USER
#  sessions: STATELESS


