spring:
  application:
    name: zipkin-server

zipkin:
  collector:
    rabbitmq:
      addresses: localhost:5672
      password: guest
      username: guest
      queue: zipkin

server:
  port: 1080

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
