spring:
  application:
    name: zipkin-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 1080

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
