spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: chendehe
server:
  port: 1111




# Number of ms to wait before throwing an exception if no connection is available.
#  tomcat:
#    max-wait: 10000
# Maximum number of active connections that can be allocated from this pool at the same time.
#    max-active: 50
# Validate the connection before borrowing it from the pool.
#    test-on-borrow: true
