spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/chendehe/ConfigurationMgr/
          search-paths: web/
          username: chendehe
          password: *********
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 1050

management:
  security:
    # 禁用actuator鉴权
    enabled: false